# 機器學習_ML_preprocessing.PolynominalFeatures
###### tags: `ML` `preprocessing` `PolynominalFeatures` `sklearn`
[官方說明](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html)

PolynominalFeatures用於將特徵擴展為多項式，平方、次方、甚至更高，有什麼好處?可以得到更好的擬合，但是結果可能就是overfitting。畢竟訓練資料集是已知的資料，而我們希望預測的那未知是不確定的，滿足訓練資料集卻不一定滿足驗證測試資料集。  
官方文件簡單的範例，如果有a、b兩個特徵做了次方，那會得到\[1, a, b, a^2, ab, b^2\]，如果我們設置interaction_only為True，那會單純得到\[1,a,b,ab\]，如果inculde_bias=False，那就不會有偏差單元1。
## IMPORT
```python
from sklearn.preprocessing import PolynomialFeatures
```
## CLASS
```python
sklearn.preprocessing.PolynomialFeatures(
    degree=2, interaction_only=False, include_bias=True)
```

## 參數說明
### degree : integer
Default = 2
多項式的級數，預設為次方。
### interaction_only : boolean
default = False
是否產生交互作用的特徵
### include_bias : boolean
default = True
是否產生偏差單元

## 屬性說明
### powers_ : array, shape (n_output_features, n_input_features)
### n_input_features_ : int
輸入的特徵總數
### n_output_features_ : int
輸出的特徵總數

## 方法說明
### fit
擬合、訓練
### fit_transform
擬合、訓練並且轉換
### get_feature_names([input_features])	
取得特徵名稱?
### get_params([deep])	
取得模型參數
### set_params(**params)	
設置模型參數
### transform(X)	
轉換特徵

## 範例  

In [2]:
#  import需求套件
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

In [21]:
#  產生一個假的特徵，為了方便演練，我們只產生一筆。
feature = np.array([[1,2]])

In [22]:
feature

array([[1, 2]])

In [30]:
#  先以預設值觀察
polynominal = PolynomialFeatures()

In [31]:
#  轉換多項式
new_feature = polynominal.fit_transform(feature)
#  確認特徵
#  應該為[1, a, b, a^2, ab, b^2]
new_feature

array([[ 1.,  1.,  2.,  1.,  2.,  4.]])

In [33]:
polynominal.get_feature_names()

['1', 'x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']

In [34]:
polynominal = PolynomialFeatures(interaction_only=True)
new_feature2 = polynominal.fit_transform(feature)
#  應該為[1,a,b,ab]
new_feature2

array([[ 1.,  1.,  2.,  2.]])

In [35]:
polynominal.get_feature_names()

['1', 'x0', 'x1', 'x0 x1']

In [36]:
polynominal = PolynomialFeatures(include_bias=False)
new_feature3 = polynominal.fit_transform(feature)
#  拿掉偏差單元了
new_feature3

array([[ 1.,  2.,  1.,  2.,  4.]])

In [37]:
polynominal.get_feature_names()

['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']